name: Install GNU Guix
description: Add GNU guix package manager to GitHub Action runner.
branding:
  icon: 'package'
  color: 'gray-dark'
inputs:
  channels:
    description: 'Guix channel description as Scheme code'
    required: false
    # Use the GitHub mirror to decrease load on Savannah.
    default: |-
      (map (lambda (chan)
             (if (guix-channel? chan)
                 (channel
                  (inherit chan)
                  (url "https://github.com/guix-mirror/guix.git"))
                 chan))
           %default-channels)
  pullAfterInstall:
    description: 'Run `guix pull` after installing Guix'
    required: false
    default: true
outputs:
  channels:
    description: 'Exact Guix channels that were used for this action.'
    value: ${{ steps.guix-describe.outputs.channels }}
runs:
  using: 'composite'
  steps:
    # The default locale on Debian and Ubuntu is "C.UTF-8" which does not exist
    # in vanilla glibc.  Change to something that works for Guix and Debuntu.
    - run: |
        wget -nv https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh -O guix-install.sh
        wget -nv https://ci.guix.gnu.org/search/latest/archive?query=spec:tarball+status:success+system:x86_64-linux+guix-binary.tar.xz -O guix-binary-nightly.x86_64-linux.tar.xz
      shell: bash
      name: Download
    - run: |
        wget "https://savannah.gnu.org/people/viewgpg.php?user_id=127547" -qO - | sudo gpg --import -
        wget "https://savannah.gnu.org/people/viewgpg.php?user_id=15145" -qO - | sudo gpg --import -
      shell: bash
      name: Fetch key
    - run: |
        export GUIX_BINARY_FILE_NAME=guix-binary-nightly.x86_64-linux.tar.xz
        sudo --preserve-env=GUIX_BINARY_FILE_NAME -- bash -c 'env --default-signal=PIPE yes "" | bash guix-install.sh'
        ls -lha /home/runner/work/_temp/_runner_file_commands/
      shell: bash
      name: Install Guix
