name: guix-install
description: Install GNU Guix
branding:
  icon: 'package'
  color: 'gray-dark'
inputs:
  channels:
    description: Guile expression representing the Guix channel(s) to pull
    required: false
    default: '%default-channels'
runs:
  using: 'composite'
  steps:
    - run: wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh -O guix-install.sh
      shell: bash
      name: Download
    - run: wget "https://sv.gnu.org/people/viewgpg.php?user_id=15145" -qO - | sudo gpg --import -
      shell: bash
      name: Fetch key
    - run: echo -e 'y\ny' | sudo bash guix-install.sh
      shell: bash
      name: Install Guix
    # Use the GitHub mirror to decrease load on Savannah. Update global guix,
    # so we get a fresh daemon as well.
    - run: |
        echo Invoking 'guix pull' with the following channel specification:
        echo
        echo "${{ inputs.channels }}" | tee /tmp/channels.scm
        echo
        sudo guix pull --url=https://github.com/guix-mirror/guix.git --fallback -C /tmp/channels.scm
      shell: bash
      name: Update Guix
    - run: sudo systemctl restart guix-daemon
      shell: bash
      name: Restart daemon
    - run: sudo guix archive --generate-key
      shell: bash
      name: Generate keys

